{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tenant-runtime.fullname" . }}
  labels:
    {{- include "tenant-runtime.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "tenant-runtime.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- range .Values.networkPolicy.ingressNamespaces }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . | quote }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        {{- range .Values.networkPolicy.egressCidrs }}
        - ipBlock:
            cidr: {{ . | quote }}
        {{- end }}
{{- end }}
